version: '3.1'

services:
  zorechka-bot:
    container_name: zorechka-bot
    build: .
    depends_on:
      - db

  db:
    container_name: zorechka-mysql
    image: mysql:5.7.27
    command: --default-authentication-plugin=mysql_native_password
    ports:
     - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: zorechka
    volumes:
      - mysql-data-volume:/var/lib/mysql

volumes:
  mysql-data-volume:
